### ISSUE TITLE
master branch failing at build-debian

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#67]
```
docker run ribose-local/mn:1.2.11 metanorma help
5
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize': Could not find rake-12.3.3 in any of the sources (Bundler::GemNotFound)
6
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
7
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
8
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
9
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
10
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
11
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
12
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
13
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
14
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
15
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
16
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
17
	from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
18
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
19
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
20
make: *** [test-mn] Error 1
21
Makefile:181: recipe for target 'test-mn' failed
22
```

**Comment by CAMOBAP795** [comment]
Fixed
