### ISSUE TITLE
Error compiling document using metanorma-docker and the OGC template

### ISSUE THREAD

**Issue by ghobona** [metanorma/metanorma-docker#69]
I am getting this error when I try to compile a document using metanorma-docker and the OGC template.

```
ogckm1@OGCKM 19-013 % docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma compile -t ogc -x xml,html,doc document.adoc
nil versions are discouraged and will be deprecated in Rubygems 4
fetching OGC 15-043r3...
fetching OGC 08-131r3...
fetching OGC 10-126r4...
fetching OGC 15-042r3...
fetching OGC 15-082...
fetching OGC 16-008...
fetching OGC 06-121r9...
[relaton-iso] ("ISO 19156") fetching...
/usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `block in to_all_parts': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `select'
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/hit_collection.rb:35:in `to_all_parts'
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/iso_bibliography.rb:159:in `isobib_results_filter'
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/iso_bibliography.rb:169:in `isobib_get1'
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/iso_bibliography.rb:49:in `get'
	from /usr/local/bundle/gems/relaton-iso-0.11.0/lib/relaton_iso/processor.rb:19:in `get'
	from /usr/local/bundle/gems/relaton-0.10.1/lib/relaton/db.rb:180:in `new_bib_entry'
	from /usr/local/bundle/gems/relaton-0.10.1/lib/relaton/db.rb:167:in `check_bibliocache'
	from /usr/local/bundle/gems/relaton-0.10.1/lib/relaton/db.rb:31:in `fetch'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:124:in `fetch_ref'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:59:in `isorefmatches'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:201:in `reference1'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:210:in `block (2 levels) in reference'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:209:in `each'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:209:in `block in reference'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:137:in `noko'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/ref.rb:208:in `reference'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/lists.rb:38:in `ulist'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:116:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/list.rb:30:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/section.rb:224:in `block in norm_ref_parse'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/section.rb:222:in `norm_ref_parse'
	from /usr/local/bundle/gems/metanorma-ogc-1.0.3/lib/asciidoctor/ogc/converter.rb:103:in `bibliography_parse'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/section.rb:80:in `block in section'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:137:in `noko'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/section.rb:61:in `section'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:116:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/base.rb:200:in `block in middle'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/base.rb:199:in `middle'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/base.rb:171:in `block in makexml1'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `new'
	from /usr/local/bundle/gems/nokogiri-1.10.9/lib/nokogiri/xml/builder.rb:254:in `with'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:137:in `noko'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/base.rb:171:in `makexml1'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/base.rb:177:in `makexml'
	from /usr/local/bundle/gems/metanorma-ogc-1.0.3/lib/asciidoctor/ogc/converter.rb:24:in `makexml'
	from /usr/local/bundle/gems/metanorma-ogc-1.0.3/lib/asciidoctor/ogc/converter.rb:55:in `document'
	from /usr/local/bundle/gems/metanorma-standoc-1.3.21/lib/asciidoctor/standoc/utils.rb:116:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:120:in `convert'
	from /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/input/asciidoc.rb:10:in `process'
	from /usr/local/bundle/gems/metanorma-ogc-1.0.3/lib/metanorma/ogc/processor.rb:26:in `input_to_isodoc'
	from /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:112:in `process_input'
	from /usr/local/bundle/gems/metanorma-1.0.0/lib/metanorma/compile.rb:17:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/lib/metanorma/cli/compiler.rb:29:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/lib/metanorma/cli/compiler.rb:33:in `compile'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/lib/metanorma/cli/command.rb:35:in `compile'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/lib/metanorma/cli.rb:60:in `start'
	from /usr/local/bundle/bundler/gems/metanorma-cli-945c4d18385d/exe/metanorma:20:in `<top (required)>'
	from /usr/local/bundle/bin/metanorma:23:in `load'
	from /usr/local/bundle/bin/metanorma:23:in `<main>'


```

**Comment by ronaldtse** [comment]
@ghobona sorry about this, I believe this was fixed here: https://github.com/relaton/relaton-iso/issues/84

@CAMOBAP795 has the new docker container been re-built?

**Comment by CAMOBAP795** [comment]
@ronaldtse @ghobona ubuntu images pushed to remote, for Debian ones I still working on a fix for https://github.com/metanorma/metanorma-docker/issues/67

@ghobona please try `docker run -v "$(pwd)":/metanorma metanorma/metanorma-ubuntu:1.2.11.1  metanorma compile -t ogc -x xml,html,doc document.adoc`

**Comment by ghobona** [comment]
@CAMOBAP795 Yes, `metanorma-ubuntu:1.2.11.1` worked fine. Thanks.

**Comment by ronaldtse** [comment]
Thanks guys!
