### ISSUE TITLE
LoadError: cannot load such file -- rake

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-docker#96]
For all samples
 - https://github.com/metanorma/mn-samples-gb/runs/1470358779?check_suite_focus=true

```
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
LoadError: cannot load such file -- rake
  /usr/local/bundle/gems/thor-1.0.1/lib/thor/rake_compat.rb:1:in `require'
  /usr/local/bundle/gems/thor-1.0.1/lib/thor/rake_compat.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:10:in `require'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:10:in `const_get'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:10:in `block in all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:10:in `map'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:10:in `all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `each'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `flat_map'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `block in all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `each'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `flat_map'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:12:in `all_modules'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/metanorma/standoc/version.rb:16:in `versioned'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/asciidoctor/standoc/base.rb:148:in `version'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/asciidoctor/standoc/base.rb:158:in `makexml1'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/asciidoctor/standoc/base.rb:166:in `makexml'
  /usr/local/bundle/gems/metanorma-gb-1.5.8/lib/asciidoctor/gb/converter.rb:27:in `makexml'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/asciidoctor/standoc/base.rb:140:in `document'
  /usr/local/bundle/gems/metanorma-standoc-1.6.3/lib/asciidoctor/standoc/utils.rb:107:in `convert'
  /usr/local/bundle/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
  /usr/local/bundle/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
  /usr/local/bundle/gems/metanorma-1.2.0/lib/metanorma/input/asciidoc.rb:24:in `process'
  /usr/local/bundle/gems/metanorma-1.2.0/lib/metanorma/processor.rb:24:in `input_to_isodoc'
  /usr/local/bundle/gems/metanorma-1.2.0/lib/metanorma/compile.rb:122:in `process_input'
  /usr/local/bundle/gems/metanorma-1.2.0/lib/metanorma/compile.rb:21:in `compile'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/lib/metanorma/cli/compiler.rb:45:in `compile_file'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/lib/metanorma/cli/compiler.rb:30:in `compile'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/lib/metanorma/cli/compiler.rb:35:in `compile'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/lib/metanorma/cli/command.rb:41:in `compile'
  /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/lib/metanorma/cli.rb:61:in `start'
  /usr/local/bundle/bundler/gems/metanorma-cli-3ba86a9d043a/exe/metanorma:20:in `<top (required)>'
  /usr/local/bundle/bin/metanorma:23:in `load'
  /usr/local/bundle/bin/metanorma:23:in `<top (required)>'
```

**Comment by CAMOBAP** [comment]
Asked question https://github.com/erikhuda/thor/issues/740

**Comment by ronaldtse** [comment]
I don't mind but `rake` is really not part of the metanorma suite (we don't use rake as a library).

**Comment by CAMOBAP** [comment]
Mysterious issue, doesn't reporoduced anymore
